-- Atölye Nahhat — seed verisi (kaynak: Atolye_Nahhat_Malzemeler_260730.xlsx)
-- 108 satır | 54 satılık · 7 ayrıldı · 47 satıldı

insert into kategoriler (slug, ad, aciklama, sira) values
  ('rendeler', 'Rendeler', 'Ahşap rendeleri, router plane ve köşe rendeleri', 1),
  ('testereler', 'El Testereleri', 'Japon ve Batı tipi el testereleri', 2),
  ('iskarpelalar', 'Iskarpelalar', 'Düz, zıvana ve kırlangıç iskarpelaları', 3),
  ('bileme-isaretleme', 'Bileme & İşaretleme', 'Bileme aparatları, nişangahlar, işaretleme bıçakları', 4),
  ('elektrikli', 'Elektrikli Aletler', 'Tezgah makineleri, akülü el aletleri ve bataryalar', 5),
  ('iskenceler', 'İşkenceler', 'Geniş yüzey, tetikli, boru tipi ve ahşap işkenceler', 6),
  ('diger', 'Diğer', 'Tezgah, el aleti setleri ve atölye aksesuarları', 7)
on conflict (slug) do nothing;

insert into urunler (slug, kategori_slug, cinsi, malzeme, marka, model, ebat, durum, piyasa_fiyat, piyasa_kaynak, satis_fiyat, stok_durumu, sira) values
  ('ahsap-rendesi-record-no-7-570x70x140', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Record', 'No 7', '570X70X140', 'kullanilmis', 22800, 'ptt', 12500, 'satildi', 10),
  ('ahsap-rendesi-record-no-6-450x75x150', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Record', 'No 6', '450X75X150', 'kullanilmis', 8500, 'nalburcuk', 6500, 'satildi', 20),
  ('ahsap-rendesi-stanley-no-5-360x60x130', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Stanley', 'No 5', '360X60X130', 'kullanilmis', 7500, 'nalburcuk', 5000, 'satilik', 30),
  ('ahsap-rendesi-stanley-n0-4-250x60x135', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Stanley', 'N0 4', '250X60X135', 'kullanilmis', 4500, 'n11', 3000, 'satilik', 40),
  ('ahsap-rendesi-faithfull-no-4-250x60x136', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Faithfull', 'No 4', '250X60X136', 'kullanilmis', 4500, 'yurtdışı', 4500, 'satilik', 50),
  ('ahsap-rendesi-roxwood-duztaban-240x25x100', 'rendeler', 'Ahşap Rendesi', 'Ahşap', 'RoxWood', 'Düztaban', '240X25X100', 'sifir', 1085, 'Starwood', 750, 'satilik', 60),
  ('ahsap-rendesi-faithfull-avucici-block-175x45x60', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Faithfull', '(Avuçiçi) Block', '175X45X60', 'kullanilmis', 2250, 'yurtdışı', 1250, 'ayrildi', 70),
  ('ahsap-rendesi-mac-allister-avucici-block-175x55x70', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Mac Allister', '(Avuçiçi) Block', '175X55X70', 'kullanilmis', 1200, 'koçtaş', 750, 'ayrildi', 80),
  ('ahsap-rendesi-suizan-japon-150x55x20', 'rendeler', 'Ahşap Rendesi', 'Ahşap', 'Suizan', 'Japon', '150X55X20', 'sifir', 1905, 'nalburcuk', 1000, 'satildi', 90),
  ('ahsap-rendesi-ucak-rende-japon-180x65x30', 'rendeler', 'Ahşap Rendesi', 'Ahşap', 'Uçak Rende', 'Japon', '180X65X30', 'sifir', 1000, NULL, 1000, 'satildi', 100),
  ('ahsap-rendesi-stanley-duz-taban-260x40x115', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Stanley', 'Düz Taban', '260X40X115', 'kullanilmis', 4037.5, 'Starwood', 2750, 'satildi', 110),
  ('ahsap-rendesi-luban-mini-bronz', 'rendeler', 'Ahşap Rendesi', 'Metal', 'Luban', 'Mini Bronz', NULL, 'kullanilmis', 6600, 'Starwood', 4500, 'ayrildi', 120),
  ('router-plane-tek-bicakli-12mm-170x85', 'rendeler', 'Router Plane', 'Metal', NULL, 'Tek Bıçaklı (12mm)', '170X85', 'az_kullanilmis', 1750, 'amazon', 1500, 'satildi', 130),
  ('router-plane-veritas-8-bicakli-tam-set-2-3-4-5-6-12-12-18mm', 'rendeler', 'Router Plane', 'Metal', 'Veritas', '8 Bıçaklı Tam Set', '2/3/4/5/6/12/12/18mm', 'sifir', 15000, 'leevalley.ca', 35000, 'ayrildi', 140),
  ('rende-temu-kose-traslama-muhtelif-bicaklar', 'rendeler', 'Rende', 'Metal', 'TEMU', 'Köşe Traşlama', 'muhtelif bıçaklar', 'sifir', 1200, 'TEMU', 1200, 'satildi', 150),
  ('rende-temu-kose-keski', 'rendeler', 'Rende', 'Metal', 'TEMU', 'Köşe Keski', NULL, 'sifir', 1000, 'TEMU', 1000, 'satildi', 160),
  ('el-testeresi-spear-jackson-zivana-testeresi-15-inch-15-ppi', 'testereler', 'El Testeresi', 'Metal', 'Spear & Jackson', 'Zıvana Testeresi', '15 inch / 15 ppi', 'sifir', 5000, 'yurtdışı', 5000, 'satilik', 170),
  ('el-testeresi-spear-jackson-panel-testeresi-22-inch-10-ppi', 'testereler', 'El Testeresi', 'Metal', 'Spear & Jackson', 'Panel Testeresi', '22 inch / 10 ppi', 'sifir', 5000, 'yurtdışı', 5000, 'satilik', 180),
  ('el-testeresi-suizan-ryoba-24cm', 'testereler', 'El Testeresi', 'Metal', 'Suizan', 'Ryoba', '24cm', 'kullanilmis', 3700, 'n11', 2250, 'satilik', 190),
  ('el-testeresi-suizan-ryoba-24cm-2', 'testereler', 'El Testeresi', 'Metal', 'Suizan', 'Ryoba', '24cm', 'kullanilmis', 3700, 'n11', 2250, 'satilik', 200),
  ('el-testeresi-suizan-dozuki-24cm', 'testereler', 'El Testeresi', 'Metal', 'Suizan', 'Dozuki', '24cm', 'kullanilmis', 6200, 'amazon', 4500, 'satilik', 210),
  ('el-testeresi-suizan-kataba-24cm', 'testereler', 'El Testeresi', 'Metal', 'Suizan', 'Kataba', '24cm', 'kullanilmis', 3250, 'amazon', 2000, 'satilik', 220),
  ('el-testeresi-ikeda-ryoba-24cm', 'testereler', 'El Testeresi', 'Metal', 'Ikeda', 'Ryoba', '24cm', 'kullanilmis', 2620, 'akustikwood', 1500, 'satilik', 230),
  ('el-testeresi-ikeda-fretsaw-24cm', 'testereler', 'El Testeresi', 'Metal', 'Ikeda', 'Fretsaw', '24cm', 'kullanilmis', 3000, 'akustikwood', 2000, 'satilik', 240),
  ('el-testeresi-wisent-ryoba-24cm', 'testereler', 'El Testeresi', 'Metal', 'Wisent', 'Ryoba', '24cm', 'kullanilmis', 1250, 'bauhaus', 600, 'satilik', 250),
  ('iskarpela-narex-40mm-duz', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', '40mm Düz', NULL, 'kullanilmis', 2450, 'amazon', 1500, 'satildi', 260),
  ('iskarpela-narex-50mm-duz', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', '50mm Düz', NULL, 'kullanilmis', 3110, 'amazon', 1750, 'satildi', 270),
  ('iskarpela-narex-10mm-duz', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', '10mm Düz', NULL, 'kullanilmis', 1500, 'amazon', 750, 'satilik', 280),
  ('iskarpela-narex-20mm-duz-kisa-avucici-armut-sapli', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', '20mm Düz', 'Kısa Avuçiçi Armut Saplı', 'az_kullanilmis', 1100, 'nalburcuk', 900, 'satilik', 290),
  ('iskarpela-narex-duz-20mm', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', 'Düz', '20mm', 'kullanilmis', 1300, 'nalburcuk', 800, 'satilik', 300),
  ('iskarpela-narex-duz-16mm', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', 'Düz', '16mm', 'kullanilmis', 1275, 'nalburcuk', 800, 'satilik', 310),
  ('iskarpela-narex-duz-12mm', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', 'Düz', '12mm', 'kullanilmis', 1300, 'nalburcuk', 800, 'satilik', 320),
  ('iskarpela-narex-duz-10mm', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', 'Düz', '10mm', 'kullanilmis', 1200, 'nalburcuk', 800, 'satilik', 330),
  ('iskarpela-narex-duz-8mm', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', 'Düz', '8mm', 'kullanilmis', 1200, 'nalburcuk', 800, 'satilik', 340),
  ('iskarpela-narex-zivana-acma-5-li-set-6-8-10-12-14', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', 'Zıvana Açma 5''li Set', '6/8/10/12/14', 'sifir', 7500, 'nalburcuk', 6000, 'satilik', 350),
  ('iskarpela-narex-dovetail-acma-3-lu-set-6-12-19', 'iskarpelalar', 'Iskarpela', 'Metal', 'Narex', 'Dovetail Açma 3''lü Set', '6/12/19', 'sifir', 8700, 'nalburcuk', 7500, 'satilik', 360),
  ('iskarpela-kirschen-two-cherries-duz-set-6-li-6-10-12-16-20-2', 'iskarpelalar', 'Iskarpela', 'Metal', 'Kirschen Two Cherries', 'Düz Set 6''lı', '6/10/12/16/20/26', 'az_kullanilmis', 11250, 'nalburcuk', 8500, 'satilik', 370),
  ('iskarpela-kirschen-two-cherries-duz-10', 'iskarpelalar', 'Iskarpela', 'Metal', 'Kirschen Two Cherries', 'Düz', '10', 'az_kullanilmis', 2910, 'nalburcuk', 1500, 'satildi', 380),
  ('iskarpela-kirschen-two-cherries-duz-20', 'iskarpelalar', 'Iskarpela', 'Metal', 'Kirschen Two Cherries', 'Düz', '20', 'az_kullanilmis', 2910, 'nalburcuk', 1500, 'satildi', 390),
  ('iskarpela-kirschen-two-cherries-duz-26', 'iskarpelalar', 'Iskarpela', 'Metal', 'Kirschen Two Cherries', 'Düz', '26', 'az_kullanilmis', 2910, 'nalburcuk', 1500, 'satildi', 400),
  ('iskarpela-markasiz-amazon-duz-12-li-set-38-32-24-22-20-18-16', 'iskarpelalar', 'Iskarpela', 'Metal', 'Markasız (Amazon)', 'Düz (12''li Set)', '38/32/24/22/20/18/16/14/12/10/8/6', 'kullanilmis', 7500, 'yurtdışından', 6000, 'satilik', 410),
  ('iskarpela-shintaro-duz-3-lu-set-japon-9-15-24', 'iskarpelalar', 'Iskarpela', 'Metal', 'Shintaro', 'Düz  3''lü Set Japon', '9/15/24', 'sifir', 4500, 'amazon', 4500, 'ayrildi', 420),
  ('iskarpela-vintage-urun-restore-edildi-duz-japon-6-14-18-22-3', 'iskarpelalar', 'Iskarpela', 'Metal', 'Vintage ürün (restore edildi)', 'Düz Japon', '6/14/18/22/30/30', 'sifir', NULL, 'muhtelif', 20000, 'satilik', 430),
  ('bileme-narex-tig-bileme-aparati', 'bileme-isaretleme', 'Bileme', 'Metal', 'Narex', 'Tığ Bileme Aparatı', NULL, NULL, 2350, 'nalburcuk', 1500, 'satilik', 440),
  ('bileme-narex-tig-bileme-aparati-2', 'bileme-isaretleme', 'Bileme', 'Metal', 'Narex', 'Tığ Bileme Aparatı', NULL, NULL, 2350, 'nalburcuk', 1500, 'satilik', 450),
  ('isaretleme-veritas-kirlangic-isaretleme-1-8', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Veritas', 'Kırlangıç İşaretleme', '1:8', 'sifir', 1000, 'leevalley.ca', 1500, 'satildi', 460),
  ('isaretleme-veritas-kirlangic-isaretleme-1-6', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Veritas', 'Kırlangıç İşaretleme', '1:6', 'sifir', 1000, 'leevalley.ca', 1500, 'satildi', 470),
  ('isaretleme-veritas-winnding-sticks', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Veritas', 'Winnding Sticks', NULL, 'sifir', 2000, 'leevalley.ca', 3500, 'ayrildi', 480),
  ('isaretleme-veritas-isaretleme-tekeri', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Veritas', 'İşaretleme Tekeri', NULL, 'sifir', 3000, 'leevalley.ca', 7500, 'satilik', 490),
  ('isaretleme-narex-isaretleme-tekeri', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Narex', 'İşaretleme Tekeri', NULL, 'kullanilmis', 3600, 'nalburcuk', 2750, 'satilik', 500),
  ('isaretleme-luban-isaretleme-tekeri', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Luban', 'İşaretleme Tekeri', NULL, 'kullanilmis', 2850, 'amazon', 2000, 'satilik', 510),
  ('isaretleme-isaretleme-tekeri', 'bileme-isaretleme', 'İşaretleme', 'Metal', NULL, 'İşaretleme Tekeri', NULL, 'az_kullanilmis', 2500, 'amazon', 2000, 'satilik', 520),
  ('isaretleme-mujingfang-roxwood-isaretleme-nisangah', 'bileme-isaretleme', 'İşaretleme', 'Ahşap', 'Mujingfang Roxwood', 'İşaretleme Nişangah', NULL, 'sifir', 1750, 'nalburcuk', 1500, 'satilik', 530),
  ('isaretleme-faithfull-isaretleme-nisangah', 'bileme-isaretleme', 'İşaretleme', 'Ahşap', 'Faithfull', 'İşaretleme Nişangah', NULL, 'sifir', 2500, 'yurt dışı', 2500, 'satilik', 540),
  ('isaretleme-luban-isaretleme-bicagi-3-lu-set', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Luban', 'İşaretleme Bıçağı 3''lü Set', NULL, 'sifir', 4500, 'starwood', 4000, 'ayrildi', 550),
  ('isaretleme-narex-isaretleme-bicagi', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Narex', 'İşaretleme Bıçağı', NULL, 'kullanilmis', 1850, 'nalburcuk', 1250, 'satilik', 560),
  ('isaretleme-faithfull-isaretleme-bicagi', 'bileme-isaretleme', 'İşaretleme', 'Metal', 'Faithfull', 'İşaretleme Bıçağı', NULL, 'sifir', 2500, 'yurtdışı', 2500, 'satilik', 570),
  ('yatar-testere-makita-mlt100n', 'elektrikli', 'Yatar Testere', 'Metal', 'Makita', 'MLT100N', NULL, 'sifir', 47200, 'teknikalet', 40000, 'satilik', 580),
  ('serit-testere-einhell-solo-tc-sb-245l', 'elektrikli', 'Şerit Testere', 'Metal', 'Einhell Solo', 'TC-SB-245L', NULL, 'kullanilmis', 14350, 'amazon', 7000, 'satildi', 590),
  ('dekupaj-testere-einhell-solo-te-js-18-80-li', 'elektrikli', 'Dekupaj Testere', 'Metal', 'Einhell Solo', 'TE-JS 18/80 Lİ', NULL, 'kullanilmis', 2850, 'muhtelif', 1900, 'satildi', 600),
  ('daire-testere-einhell-solo-te-cs-18-165-1-li', 'elektrikli', 'Daire Testere', 'Metal', 'Einhell Solo', 'TE-CS 18/165-1 Lİ', NULL, 'kullanilmis', 3800, 'amazon', 2500, 'satildi', 610),
  ('planya-einhell-solo-te-pl-18-82-li', 'elektrikli', 'Planya', 'Metal', 'Einhell Solo', 'TE.-PL 18/82 LI', NULL, 'kullanilmis', 4250, 'amazon', 2750, 'satilik', 620),
  ('civi-tabancasi-einhell-havali-tc-pn-50', 'elektrikli', 'Çivi Tabancası', 'Metal', 'Einhell (havalı)', 'TC PN 50', NULL, 'az_kullanilmis', 4150, 'amazon', 2750, 'satilik', 630),
  ('freze-einhell-solo-tp-ro-18-li-bl', 'elektrikli', 'Freze', 'Metal', 'Einhell Solo', 'TP-RO 18 Li BL', NULL, 'kullanilmis', 5040, 'hepsiburada', 3000, 'satildi', 640),
  ('freze-einhell-solo-tp-ro-18-li-bl-2', 'elektrikli', 'Freze', 'Metal', 'Einhell Solo', 'TP-RO 18 Li BL', NULL, 'kullanilmis', 5040, 'hepsiburada', 3500, 'satildi', 650),
  ('freze-standi-rox-wood', 'elektrikli', 'Freze Standı', 'Ahşap', 'Rox Wood', NULL, NULL, 'kullanilmis', 4750, 'starwood', 2500, 'satildi', 660),
  ('taslama-einhell-solo-te-ag-18-115-q-li', 'elektrikli', 'Taşlama', 'Metal', 'Einhell Solo', 'TE-AG 18/115 Q Li', NULL, 'kullanilmis', 2450, 'amazon', 1600, 'satilik', 670),
  ('gonye-testere-bosch-gcm-305-216d', 'elektrikli', 'Gönye Testere', 'Metal', 'Bosch', 'GCM 305-216D', NULL, 'kullanilmis', 18900, 'hepsiburada', 12500, 'satilik', 680),
  ('gonye-testere-standi-bosch-gta-2600', 'elektrikli', 'Gönye Testere Standı', 'Metal', 'Bosch', 'GTA 2600', NULL, 'kullanilmis', 7500, 'amazon', 5000, 'satilik', 690),
  ('dik-matkap-bosch-pbd-40', 'elektrikli', 'Dik Matkap', 'Metal', 'Bosch', 'PBD 40', NULL, 'kullanilmis', 12000, 'n11', 8000, 'satilik', 700),
  ('yassi-dubel-makinasi-einhell-solo-te-bj-18li', 'elektrikli', 'Yassı Dübel Makinası', 'Metal', 'Einhell Solo', 'TE-BJ 18Li', NULL, 'sifir', 3250, 'amazon', 2150, 'satilik', 710),
  ('vidalama-matkap-einhell-solo-te-cd-18-40-li-bl', 'elektrikli', 'Vidalama/Matkap', 'Metal', 'Einhell Solo', 'TE-CD 18/40 LI/BL', NULL, 'kullanilmis', 2000, 'amazon', 1000, 'satilik', 720),
  ('darbeli-vidalama-einhell-solo-te-ci-18-1-li', 'elektrikli', 'Darbeli Vidalama', 'Metal', 'Einhell Solo', 'TE-CI 18/1 LI', NULL, 'kullanilmis', 2000, 'amazon', 1000, 'satildi', 730),
  ('darbeli-matkap-einhell-solo-tp-cd-18-50-li-bl', 'elektrikli', 'Darbeli Matkap', 'Metal', 'Einhell Solo', 'TP-CD 18/50 LI BL', NULL, 'kullanilmis', 2500, 'amazon', 1250, 'satildi', 740),
  ('ekzantrik-zimpara-einhell-solo-te-rs-18-li', 'elektrikli', 'Ekzantrik Zımpara', 'Metal', 'Einhell Solo', 'TE-RS 18/Li', NULL, 'kullanilmis', 1750, 'amazon', 1000, 'satilik', 750),
  ('batarya-einhell-power-x18-v-5-2-ah-li-on', 'elektrikli', 'Batarya', 'Metal', 'Einhell', 'Power X18 V 5.2 Ah Li-on', NULL, 'kullanilmis', 4500, 'amazon', 3000, 'satilik', 760),
  ('batarya-einhell-power-x18-v-5-2-ah-li-on-2', 'elektrikli', 'Batarya', 'Metal', 'Einhell', 'Power X18 V 5.2 Ah Li-on', NULL, 'kullanilmis', 4500, 'amazon', 3000, 'satilik', 770),
  ('batarya-einhell-power-x18-v-5-2-ah-li-on-3', 'elektrikli', 'Batarya', 'Metal', 'Einhell', 'Power X18 V 5.2 Ah Li-on', NULL, 'kullanilmis', 4500, 'amazon', 3000, 'satilik', 780),
  ('sarj-cihazi-einhell-18v-3a-power-x', 'elektrikli', 'Şarj Cihazı', 'Metal', 'Einhell', '18V 3A Power-X', NULL, 'kullanilmis', 4500, 'amazon', 3000, 'satilik', 790),
  ('punch-seti-bosch-power-change-plus-x9', 'diger', 'Punch Seti', 'Metal', 'Bosch', 'Power change Plus X9', NULL, 'az_kullanilmis', 5750, 'amazon', 3750, 'satilik', 800),
  ('anahtar-seti-husky-12-parca', 'diger', 'Anahtar Seti', 'Metal', 'Husky', '12 parça', NULL, 'sifir', 5000, 'yurt dışı', 4000, 'satilik', 810),
  ('push-block-grr-ripper-ayarlanabilir', 'diger', 'Push Block', 'Plastik', 'Grr-Ripper', 'Ayarlanabilir', NULL, 'sifir', 3500, 'yurt dışı', 6000, 'satilik', 820),
  ('push-block-grr-ripper-ayarlanabilir-2', 'diger', 'Push Block', 'Plastik', 'Grr-Ripper', 'Ayarlanabilir', NULL, 'sifir', 3500, 'yurt dışı', 6000, 'satilik', 830),
  ('iskence-bessey-genis-yuzey-30cm', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Geniş Yüzey', '30cm', 'kullanilmis', 2250, 'yapidukkani', 1000, 'satildi', 840),
  ('iskence-bessey-genis-yuzey-30cm-2', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Geniş Yüzey', '30cm', 'kullanilmis', 2250, 'yapidukkani', 1000, 'satildi', 850),
  ('iskence-bessey-genis-yuzey-60cm', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Geniş Yüzey', '60cm', 'kullanilmis', 3000, 'yapidukkani', 1150, 'satildi', 860),
  ('iskence-bessey-genis-yuzey-60cm-2', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Geniş Yüzey', '60cm', 'kullanilmis', 3000, 'yapidukkani', 1250, 'satildi', 870),
  ('iskence-bessey-tetikli-30cm', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Tetikli', '30cm', 'kullanilmis', 2100, 'yapidukkani', 1000, 'satildi', 880),
  ('iskence-bessey-tetikli-30cm-2', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Tetikli', '30cm', 'kullanilmis', 2100, 'yapidukkani', 1000, 'satildi', 890),
  ('iskence-bessey-tetikli-30cm-3', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Tetikli', '30cm', 'kullanilmis', 2100, 'yapidukkani', 1000, 'satildi', 900),
  ('iskence-bessey-tetikli-30cm-4', 'iskenceler', 'İşkence', 'Metal', 'Bessey', 'Tetikli', '30cm', 'kullanilmis', 2100, 'yapidukkani', 1000, 'satildi', 910),
  ('iskence-rox-wood-genis-yuzey-100cm', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '100cm', 'kullanilmis', 2000, 'starwood', 1000, 'satildi', 920),
  ('iskence-rox-wood-genis-yuzey-100cm-2', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '100cm', 'kullanilmis', 2000, 'starwood', 1000, 'satildi', 930),
  ('iskence-rox-wood-genis-yuzey-100cm-3', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '100cm', 'kullanilmis', 2000, 'starwood', 1000, 'satildi', 940),
  ('iskence-rox-wood-genis-yuzey-100cm-4', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '100cm', 'kullanilmis', 2000, 'starwood', 1000, 'satildi', 950),
  ('iskence-rox-wood-genis-yuzey-60cm', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '60cm', 'kullanilmis', 2000, 'starwood', 1000, 'satildi', 960),
  ('iskence-rox-wood-genis-yuzey-60cm-2', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '60cm', 'kullanilmis', 2000, 'starwood', 1000, 'satildi', 970),
  ('iskence-rox-wood-genis-yuzey-40cm', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '40cm', 'kullanilmis', 1750, 'starwood', 800, 'satildi', 980),
  ('iskence-rox-wood-genis-yuzey-40cm-2', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Geniş Yüzey', '40cm', 'kullanilmis', 1750, 'starwood', 800, 'satildi', 990),
  ('iskence-rox-wood-vidali-ahsap-iskence-12-inch', 'iskenceler', 'İşkence', 'Ahşap', 'Rox Wood', 'Vidalı Ahşap İşkence', '12 inch', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1000),
  ('iskence-rox-wood-vidali-ahsap-iskence-12-inch-2', 'iskenceler', 'İşkence', 'Ahşap', 'Rox Wood', 'Vidalı Ahşap İşkence', '12 inch', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1010),
  ('iskence-rox-wood-vidali-ahsap-iskence-12-inch-3', 'iskenceler', 'İşkence', 'Ahşap', 'Rox Wood', 'Vidalı Ahşap İşkence', '12 inch', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1020),
  ('iskence-rox-wood-vidali-ahsap-iskence-12-inch-4', 'iskenceler', 'İşkence', 'Ahşap', 'Rox Wood', 'Vidalı Ahşap İşkence', '12 inch', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1030),
  ('iskence-rox-wood-boru-tipi-iskence-3-4-inch-150cm', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Boru Tipi İşkence', '3/4 inch - 150cm', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1040),
  ('iskence-rox-wood-boru-tipi-iskence-3-4-inch-150cm-2', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Boru Tipi İşkence', '3/4 inch - 150cm', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1050),
  ('iskence-rox-wood-boru-tipi-iskence-3-4-inch-150cm-3', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Boru Tipi İşkence', '3/4 inch - 150cm', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1060),
  ('iskence-rox-wood-boru-tipi-iskence-3-4-inch-150cm-4', 'iskenceler', 'İşkence', 'Metal', 'Rox Wood', 'Boru Tipi İşkence', '3/4 inch - 150cm', 'kullanilmis', 1200, 'starwood', 500, 'satildi', 1070),
  ('tezgah-atolye-fehmi-tasinabilir-600x700', 'diger', 'Tezgah', 'Ahşap', 'Atölye Fehmi', 'Taşınabilir 600X700', NULL, 'kullanilmis', 25000, 'Atölye Fehmi', 17500, 'satilik', 1080)
on conflict (slug) do nothing;